version: '3'
services:

  scrapyd:
    image: vimagick/scrapyd:latest
    ports:
      - "6800:6800"
    volumes:
      - ~/scrapy_flyertalk_data/scrapyd:/data
      - ./scrapyd.conf:/etc/scrapyd/scrapyd.conf

  scrapydweb:
    image: ryanvin/scrapydweb:latest
    ports:
      - "5001:5000"
    volumes:
      - ~/scrapy_flyertalk_data/scrapydWeb:/data
      - ~/scrapy_flyertalk_data/scrapyd:/data/scrapyd      
      - ./scrapydweb_settings_v10.py:/app/scrapydweb_settings_v10.py
    environment:
      SCRAPYD_SERVERS: "[ http://scrapyd:6800 ] "

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/scrapy_flyertalk_data/mongo_db:/data/db
      
  mongo_express:
    image: mongo-express:latest
    volumes:
      - ~/scrapy_flyertalk_data/mongo-express:/data/db    
    ports:
      - "8081:8081"
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin # Set your MongoDB admin username
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password # Set your MongoDB admin password
      ME_CONFIG_MONGODB_SERVER: mongo