version: '3'
services:

  scrapyd:
    image: vimagick/scrapyd:latest
    ports:
      - "6800:6800"
    volumes:
      - ~/scrapy_flyertalk_data/scrapyd:/data
      - ./scrapyd.conf:/etc/scrapyd/scrapyd.conf
    environment:
      MONGO_USERNAME: ${MONGO_SCRAPY_USER}
      MONGO_PASSWORD: ${MONGO_SCRAPY_PWD}
      DATA_ROOT_DIR: '/data'
      MONGO_HOST: 'mongo'

  scrapydweb:
    image: ryanvin/scrapydweb:latest
    ports:
      - "5001:5000"
    volumes:
      - ~/scrapy_flyertalk_data/scrapydWeb:/data
      - ~/scrapy_flyertalk_data/scrapyd:/data/scrapyd      
      - ./scrapydweb_settings_v10.py:/app/scrapydweb_settings_v10.py
    environment:
      SCRAPYD_SERVERS: "[ http://scrapyd:6800 ] "
      USERNAME: ${SCRAPYDWEB_USERNAME}
      PASSWORD: ${SCRAPYDWEB_PASSWORD}      
      DATA_ROOT_DIR: '/data'

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/scrapy_flyertalk_data/mongo_db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js           
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_SCRAPY_USER: ${MONGO_SCRAPY_USER}
      MONGO_SCRAPY_PWD: ${MONGO_SCRAPY_PWD}
      MONGO_INITDB_DATABASE: 'flyertalk'
      
  mongo_express:
    image: mongo-express:latest
    volumes:
      - ~/scrapy_flyertalk_data/mongo-express:/data/db    
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}